language: python
install:
    - python setup.py develop
    - pip install coveralls

python:
    - "2.6"
    - "2.7"

script:
    - nosetests -s

after_success:
    - coverage run --source=flask_babel setup.py -q nosetests
    - coveralls

notifications:
    email: false
